pages/urls.py
from .views import *
from django.urls import  path
urlpatterns = [
    path('' , HomeView.as_view() , name='home'),
    path('about/' , AboutView.as_view() , name='about'),
    path('contact/' , ContactView.as_view() , name='contact'),
    path('order/', OrderView.as_view() , name='order'),
    path('profile/' , ProfileView.as_view() , name='profile'),
    path('profileInfo/' , ProfileInfoView.as_view() , name='profileInfo'),
    path('profileStatus/' , ProfileStatusView.as_view() , name='profileStatus'),
    path('signinStaff/' , SignInStaffView.as_view() , name='signInStaff'),
    path('profileStaff/' , ProfileStaffView.as_view() , name = 'profileStaff'),
    path('profileStaffStatus/' , ProfileStaffStatusView.as_view() , name = 'profileStaffStatus'),
    path('profileStaffInfo/' , ProfileStaffInfoView.as_view() , name = 'profileStaffInfo'),
    path('profileStaffNewReq/' , ProfileStaffNewReqView.as_view() , name = 'profileStaffNewReq'),
    path('profileManagerInfo/' , ProfileManagerInfo.as_view() , name='profileManagerInfo'),
    path('profileManagerStatus/' , ProfileManagerStatus.as_view() , name="profileManagerStatus"),
    path('profileManagerVol/' , ProfileManagerVol.as_view() , name='profileManagerVol'),
    path('detailsOfVol/<int:pk>',DetailsOfVol.as_view() , name='detailsOfVol'),
    path('reqsended/<int:id>/',reqSended,name='reqsended'),
    path('reqaccept/<int:id>/',reqAccept,name='reqaccept'),
    path('acceptdriver/<int:id>/',acceptDriver,name='acceptdriver'),
    path('denydriver/<int:id>/',denyDriver,name='denydriver'),
]

pickupapp/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('pages.urls')),
    path('',include('account.urls')),
    path('',include('django.contrib.auth.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import HttpResponse
import requests
from django_jalali.db import models as jmodels

class Address(models.Model):
    name=models.CharField(max_length=50,null=True,blank=True)
    lat = models.FloatField(null=True,blank=False)
    long = models.FloatField(null=True,blank=False)
    formated=models.CharField(max_length=255,null=True,blank=True)
    def __str__(self):
        return str(self.name)
@receiver(post_save,sender=Address)
def setName(sender, instance, created, **kwargs):
    if created:
        data={'lat':instance.lat,'lng':instance.long}
        r=requests.get('https://api.neshan.org/v5/reverse?lat={}&lng={}'.format(instance.lat,instance.long),
        headers ={

        "Api-Key": "service.03aa018ac2c2439c9270d67fb8282bfd"
        }
        )
        try:
            instance.name=r.json()['route_name']
            instance.formated=r.json()['formatted_address']
            instance.save()
        except:
            pass




class Request(models.Model):
    user=models.ForeignKey('account.CustomUser', on_delete=models.CASCADE)
    driver=models.ForeignKey('account.CustomUser',on_delete=models.SET_NULL,null=True,blank=True,related_name='req_driver')
    req_date=jmodels.jDateField(auto_now_add=True)
    package=models.ForeignKey('Package',on_delete=models.CASCADE)
    type=models.CharField(max_length=50,choices=[('regular','معمولی'),('instance','فوری')])
    sAddress=models.ForeignKey('Address',on_delete=models.CASCADE,related_name='saddress')
    dAddress=models.ForeignKey('Address',on_delete=models.CASCADE,related_name='daddress')
    sended=models.BooleanField(default=False)
    accepted=models.BooleanField(default=False)
    price=models.IntegerField()

    def __str__(self):
        return str(self.user)+" "+self.type
    def get_type(self):
        TYPE_CHOICES = [
            ('regular', 'معمولی'),
            ('instance', 'فوری'),
        ]
        type=dict(TYPE_CHOICES)
        return type.get(self.type)


class Package(models.Model):
    weight=models.CharField(max_length=50,choices=[('small','کوچک'),('normal','متوسط'),('large','بزرگ')])
    def __str__(self):
        return self.weight

templates/About.html
{% extends 'base.html' %}{% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/aboutStyle.css' %}" />
<link rel="stylesheet" href="{% static 'css/aboutResponsiveStyle.css' %}" />
{% endblock linkContent %}
<span></span>
{% block titleContent %}About{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotal">
  <div id="wrapperOfAboutContent">
    <div id="wrapperOfAboutText">
      <h2>درباره ما</h2>
      <p>
        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده
        از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و
        سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای
        متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه
        درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با
        نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان
        خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد،
      </p>
    </div>
  </div>
</div>

{% endblock mainContent %}

templates/Contact.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/contactStyle.css' %}" />
<link rel="stylesheet" href="{% static 'css/contactResponsiveStyle.css' %}" />
{% endblock linkContent %}
<span></span>
{% block titleContent %}Contact{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotal">
  <div id="wrapperOfContactContent">
    <img src="{% static 'image/contact.jpg' %}" id="contactPic" />
    <div id="wrapperOfContextContact">
      <img src="{% static 'image/phone.jpg' %}" id="phonePic" />
      <div class="wrapperEachBox">
        <h2>تماس با ما</h2>
        <p>تلفن پشتیبانی : 91079550 - 021</p>
        <p>فکس : 89774788 - 021</p>
        <p>پست الکترونیک : info@getgo.cab</p>
      </div>
      <div class="wrapperEachBox">
        <h2>دفتر امور رانندگان پیک و مشتریان</h2>
        <p>شماره تماس : 91079550 - 021</p>
        <p>خدمات مربوط به مشتریان به صورت غیر حضوری عرضه میشود .</p>
      </div>
      <div class="wrapperEachBox">
        <h2>دفتر گت گات در تهران</h2>
        <p>خیابان سازمان آب نرسیده به آیت الله کاشانی</p>
        <p>پلاک 265</p>
        <p>تلفن پشتیبانی : 96642 - 021</p>
      </div>
    </div>
  </div>
</div>

{% endblock mainContent %}

templates/Order.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/orderStyle.css' %}" />
<link rel="stylesheet" href="{% static 'css/orderResponsiveStyle.css' %}" />
{% endblock linkContent %}
<span></span>
{% block titleContent %}Order{% endblock titleContent %}
<span></span>
{% block mainContent %}
<!-- Map -->
<div id="wrapperTotalMap">
  <di id="wrapperOfMoreInfo">
    <div id="totalWrapperContext">
      <div class="wrapperInfoPart">
        <p>مبدا</p>
        <img
          src="{% static 'image/LocationIcon1.png' %}"
          class="locationIconInfo"
          id="locationIconOne"
        />
      </div>
      <div class="wrapperInfoPart">
        <p>مقصد</p>
        <img
          src="{% static 'image/LocationIcon2.png' %}"
          class="locationIconInfo"
        />
      </div>
    </div>

    <div id="wrapperTextContent">
      <h3>راهنمایی :</h3>
      <p>برای تغییر آدرس علامت های مبدا و مقصد را روی نقشه حرکت دهید</p>
    </div>
  </di>
  <div class="wrapperMapPic" id="map" style="z-index: 0"></div>
</div>

<div id="wrapperOfBoxInfo">
  <form id="formPart" method="post">
    {% csrf_token %}
    <div id="wrapperOfTypeOfDelivery">
      <div class="wrapperOptions">
        <p>نوع ارسال :</p>
        {{ reqform.type }}
      </div>

      <div class="wrapperOptions">
        <p>اندازه بسته</p>
        {{ pacform.weight }}
      </div>
    </div>
    <div id="wrapperOfPriceOfBox">
      <h3 style="color: #2b4162">مبلغ نهایی :</h3>
      <p id="wrapperPrice">
        <input type="text" readonly id="price" name="price" /> تومان
        <button type="button" id="calcprice">محاسبه قیمت</button>
      </p>
      <button
        type="submit"
        id="payBtn"
        onmouseenter="textOfBtnEnterMouse()"
        onmouseleave="textOfBtnLeaveMouse()"
      >
        <!-- <img src="../static/image/box1.png" id="truckPic" /> -->
        پرداخت
        <!-- <img src="{% static 'image/box1.png' %}" id="boxPic" /> -->
      </button>
    </div>
    <input type="hidden" name="slat" id="slat" />
    <input type="hidden" name="slong" id="slong" />
    <input type="hidden" name="dlat" id="dlat" />
    <input type="hidden" name="dlong" id="dlong" />
  </form>
</div>
{% endblock mainContent %}
<span></span>
{% block scriptContent %}
<script src="{% static 'JS/orderScripts.js' %}"></script>
{% endblock scriptContent %}

templates/base.html
{% load static %}
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/baseStyle.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/responsiveStyle.css' %}"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    {% block linkContent %}{% endblock linkContent %}
    <title>{% block titleContent %}{% endblock titleContent %}</title>
</head>
<body onresize="resizingWindow()">
<header id="headerPart">
    <img
            src="{% static 'image/MenuIcon.svg' %}"
            id="menuIcon"
            onclick="clickingMenuBtn()"
    />
    <!-- <img src="{% static 'image/cross-svgrepo-com1.svg' %}" id="menuIcon" /> -->

    <ul id="menuPart">
        <li>
            <a
                    href="{% url 'home' %}"
                    onmouseenter="hoveringMenu(`recOne`)"
                    onmouseleave="undoHoveringMenu(`recOne`)"
            >خانه</a
            >
            <div class="rec" id="recOne"></div>
        </li>
        <li>
            <a
                    href="{% url 'signInStaff' %}"
                    onmouseenter="hoveringMenu(`recTwo`)"
                    onmouseleave="undoHoveringMenu(`recTwo`)"
            >ثبت نام پیک</a
            >
            <div class="rec" id="recTwo"></div>
        </li>
        <li>
            <a
                    href="{% url 'about' %}"
                    onmouseenter="hoveringMenu(`recThree`)"
                    onmouseleave="undoHoveringMenu(`recThree`)"
            >درباره ما</a
            >
            <div class="rec" id="recThree"></div>
        </li>
        <li>
            <a
                    href="{% url 'contact' %}"
                    onmouseenter="hoveringMenu(`recFour`)"
                    onmouseleave="undoHoveringMenu(`recFour`)"
            >تماس با ما</a
            >
            <div class="rec" id="recFour"></div>
        </li>
    </ul>

    <div id="leftPartOfHeader">
        {% if user.is_authenticated %}
        
        {% if user.is_superuser %}
        
        <a href="{% url 'profileManagerInfo' %}" id="btnSignIn">پروفایل</a>
            {% elif user.is_driver %}
                <a href="{% url 'profileStaff' %}" id="btnSignIn">پروفایل</a>
            {% else %}
                <a href="{% url 'profile' %}" id="btnSignIn">پروفایل</a>
            {% endif %}
        {% else %}
            <a><img src="{% static 'image/UserIcon.svg' %}" id="userIcon"/></a>
            <a href="{% url 'login' %}" id="btnSignIn">ورود / ثبت نام</a>
        {% endif %}
        <img
                src="{% static 'image/Logo2.png' %}"
                id="logoPart"
                onclick='location.href="/"'
        />
    </div>
</header>

<div id="wrapperSideMenu">
    <ul id="sideMenu">
        <a href="{% url 'home' %}">
            <li>خانه</li>
        </a>
        <a href="{% url 'signInStaff' %}">
            <li>ثبت نام پیک</li>
        </a>
        <a href="{% url 'about' %}">
            <li>درباره ما</li>
        </a>
        <a href="{% url 'contact' %}" style="border-radius: 0 0 0 0.5rem"
        >
            <li>تماس با ما</li>
        </a
        >
    </ul>
</div>

{% block mainContent %} {% endblock mainContent %}

<footer id="wrapperOfFooter">
    <img src="{% static 'image/Footer.svg' %}" id="footerPart"/>
    <div id="wrapperOfContentFooter">
        <div id="wrapperOfFooterInfo">
            <p>پشتیبانی : 44024 - 021</p>
            <p>شرکت : 88575160 - 021</p>
        </div>

        <div id="wrapperOfFooterPic">
            <img
                    src="{% static 'image/عضو اتحادیه کشوری.png' %}"
                    alt=""
                    class="picOfFooter"
            />
            <img
                    src="{% static 'image/نشان ملی ثبت.png' %}"
                    alt=""
                    class="picOfFooter"
            />
            <img
                    src="{% static 'image/نماد اعتماد.png' %}"
                    alt=""
                    class="picOfFooter"
            />
        </div>
    </div>
</footer>
<script src="{% static 'JS/baseScript.js' %}"></script>
<script src="{% static 'JS/jquery-3.7.0.min.js' %}"></script>
<script src="{% static "JS/base.js" %}"></script>
{% block scriptContent %} {% endblock scriptContent %}
</body>
</html>

templates/detailsOfVol.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/detailsOfVolStyle.css' %}" />
<!-- <link rel="stylesheet" href="{% static 'css/contactResponsiveStyle.css' %}" /> -->
{% endblock linkContent %}
<span></span>
{% block titleContent %}Contact{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotalFormDetail">
  <div class="wrapperRows">
    <img src="{{driverinfo.avatar.url}}" id="profileImage" />
    <img src="{{driverinfo.licence.url}}" id="licenseImage" />
  </div>

  <div class="wrapperRows">
    <p class="textOfContent">نام : {{driverinfo.user.first_name}}</p>
    <p class="textOfContent">نام خانوادگی : {{driverinfo.user.last_name}}</p>
    <p class="textOfContent">تلفن همراه : {{driverinfo.user.phone_no}}</p>
  </div>

  <div class="wrapperRows">
    <p class="textOfContent">کد ملی : {{driverinfo.user.nationalId}}</p>
    <p class="textOfContent">ایمیل: {{driverinfo.email}}</p>
    <p class="textOfContent">آدرس : {{driverinfo.address.formated}}</p>
  </div>

  <div class="wrapperRowsLast">
    <p class="textOfContentLast">
      لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
      طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان
      که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با
      هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته
      حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها
      شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ
      پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و
      دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد
      نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای
      موجود طراحی اساسا مورد استفاده قرار گیرد.
    </p>
  </div>

  <div class="wrapperRows">
    <form action="{% url 'acceptdriver' driverinfo.id %}" method="post">
      {%csrf_token%}
      <button class="btnStyles" id="submitBtn" type="submit">ثبت رزومه</button>
    </form>
    <form action="{% url 'denydriver' driverinfo.id %}" method="post">
      {%csrf_token%}
      <button class="btnStyles" id="denyBtn" type="submit">رد رزومه</button>
    </form>
  </div>
</div>
{% endblock mainContent %}

templates/profile.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/profileStyle.css' %}" />
<link rel="stylesheet" href="{% static 'css/profileResponsiveStyle.css' %}" />
{% endblock linkContent %}
<span></span>
{% block titleContent %}profile{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotalMenuForProfile">
  <ul id="wrapperMenu">
    <a href="{% url 'profile' %}" style="color: #aad2fc"><li>معرفی</li></a>
    <a href="{% url 'profileStatus' %}"><li>وضعیت ارسال</li></a>
    <a href="{% url 'profileInfo' %}"><li>اطلاعات کاربری</li></a>
    <a href="{% url 'logout' %}" style="color: #ba2c46"><li>خروج</li></a>
  </ul>
  <div id="wrapperBodyOfInfo">
    <h3 id="wrapperHead">کاربر گرامی ، {{ user.first_name }} خوش آمدید !</h3>
    <p id="wrapperTotalText">
      لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
      طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان
      که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با
      هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته
      حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها
      شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ
    </p>

    <h3 id="wrapperHead">عضو تیم شوید</h3>
    {% if user.driverinfo %}
    <p id="wrapperTotalText">
      درخواست شما برای پیوستن به عنوان راننده {% if user.is_driver %} قبول شده.
      {% else %} در حال بررسی میباشد. {% endif %}
    </p>
    {% else %}
    <p id="wrapperTotalText">
      لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
      طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان
      که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با
      هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته
      حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها
      شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ
    </p>
    <a href="{% url 'signInStaff' %}">عضو تیم شو</a>
    {% endif %}
  </div>
</div>
{% endblock mainContent %}

templates/profileInfo.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/profileInfoStyle.css' %}" />
<link
  rel="stylesheet"
  href="{% static 'css/profileInfoResponsiveStyle.css' %}"
/>
{% endblock linkContent %}
<span></span>
{% block titleContent %}profile{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotalMenuForProfile">
  <ul id="wrapperMenu">
    <a href="{% url 'profile' %}">
      <li>معرفی</li>
    </a>
    <a href="{% url 'profileStatus' %}">
      <li>وضعیت ارسال</li>
    </a>
    <a href="{% url 'profileInfo' %}" style="color: #aad2fc">
      <li>اطلاعات کاربری</li>
    </a>
    <a href="{% url 'logout' %}" style="color: #ba2c46"><li>خروج</li></a>
  </ul>
  <form id="wrapperBodyOfInfo" method="post">
    {% csrf_token %}
    <div class="wrapperRows">
      <div class="wrapperInputs">
        <label>نام</label>
        <input
          type="text"
          class="inputStyle"
          name="first_name"
          value="{{ user.first_name }}"
        />
      </div>
      <div class="wrapperInputs">
        <label>نام خانوادگی</label>
        <input
          type="text"
          class="inputStyle"
          name="last_name"
          value="{{ user.last_name }}"
        />
      </div>
    </div>
    <div class="wrapperRows">
      <div class="wrapperInputs">
        <label>تلفن همراه</label>
        <input type="text" class="inputStyle" value='{{ user.phone_no }}'/>
      </div>
      <div class="wrapperInputs">
        <label>ایمیل</label>
        <input type="email" class="inputStyle" name="email" value='{{ user.driverinfo.email }}' />
      </div>
    </div>
    <div class="wrapperbutton">
      <button type="submit" id="saveChangesBtn">ثبت تغییرات</button>
    </div>
  </form>
</div>
{% endblock mainContent %}

templates/profileManagerInfo.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/profileStaffInfoStyle.css' %}" />
<link
  rel="stylesheet"
  href="{% static 'css/profileStaffInfoResponsiveStyle.css' %}"
/>
{% endblock linkContent %}
<span></span>
{% block titleContent %}profile{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotalMenuForProfile">
  <ul id="wrapperMenu">
    <a href="{% url 'profileManagerInfo' %}" style="color: #aad2fc"
      ><li>اطلاعات کاربری</li></a
    >
    <a href="{% url 'profileManagerStatus' %}"><li>وضعیت درخواست</li></a>
    <a href="{% url 'profileManagerVol' %}"><li>داوطلبان مجموعه</li></a>
    <a href="{% url 'logout' %}" style="color: #ba2c46"><li>خروج</li></a>
  </ul>
  <form id="wrapperBodyOfInfo" method="post">
    {% csrf_token %}
    <div class="wrapperRows">
      <div class="wrapperInputs">
        <label>نام</label>
        <input
          type="text"
          class="inputStyle"
          name="first_name"
          value="{{ user.first_name }}"
        />
      </div>
      <div class="wrapperInputs">
        <label>نام خانوادگی</label>
        <input
          type="text"
          class="inputStyle"
          name="last_name"
          value="{{ user.last_name }}"
        />
      </div>
    </div>
    <div class="wrapperRows">
      <div class="wrapperInputs">
        <label>تلفن همراه</label>
        <input type="text" class="inputStyle" value='{{user.phone_no}}' name='phone_no'/>
      </div>
      <div class="wrapperInputs">
        <label>ایمیل</label>
        <input type="email" class="inputStyle" name="email" value=' {{user.email}} '/>
      </div>
    </div>
    <div class="wrapperbutton">
      <button type="submit" id="saveChangesBtn">ثبت تغییرات</button>
    </div>
  </form>
</div>
{% endblock mainContent %}

templates/profileStatus.html
{% extends 'base.html' %} {% load static %} {% block linkContent %}
<link rel="stylesheet" href="{% static 'css/profileStatusStyle.css' %}" />
<link
  rel="stylesheet"
  href="{% static 'css/profileStatusResponsiveStyle.css' %}"
/>
{% endblock linkContent %}
<span></span>
{% block titleContent %}profile{% endblock titleContent %}
<span></span>
{% block mainContent %}
<div id="wrapperTotalMenuForProfile">
  <ul id="wrapperMenu">
    <a href="{% url 'profile' %}"><li>معرفی</li></a>
    <a href="{% url 'profileStatus' %}" style="color: #aad2fc">
      <li>وضعیت ارسال</li>
    </a>
    <a href="{% url 'profileInfo' %}"><li>اطلاعات کاربری</li></a>
    <a href="{% url 'logout' %}" style="color: #ba2c46"><li>خروج</li></a>
  </ul>
  <div id="wrapperBodyOfInfo">
    <table id="wraperTableOfStatus">
      <tr>
        <th>شماره درخواست</th>
        <th>مبدا</th>
        <th>مقصد</th>
        <th>نام پیک</th>
        <th>نوع ارسال</th>
        <th>تاریخ درخواست</th>
        <th>وضعیت بسته</th>
      </tr>
      {% for request in user.request_set.all %}

      <tr>
        <td>{{ request.id }}</td>
        <td>{{ request.sAddress.name }}</td>
        <td>{{ request.dAddress.name }}</td>
        <td>
          {% if request.req_driver %}{{ request.req_driver }}{% else %}در انتظار
          قبول درخواست {% endif %}
        </td>
        <td>{{ request.get_type }}</td>
        <td>{{ request.req_date }}</td>
        {% if request.sended %}
        <td class="successMessage">ارسال موفق</td>

        {% else %}

        <td class="unsuccessMessage">در مسیر مقصد</td>
        {% endif %}
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock mainContent %}